root = "."

[run]
  args_bin = []
  cmd = "go run server.go"
  delay = 1000
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
